version: '3'
services:
  eureka-server:
    image: eureka-server
    build: ./eureka-server
    ports:
      - "8761:8761"

  user-service:
    image: user-service
    build: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server

  task-service:
    image: task-service
    build: ./task-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server

  notification-service:
    image: notification-service
    build: ./notification-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
